//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITestProject.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class endpoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal endpoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APITestProject.Data.endpoints", typeof(endpoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://postman-echo.com.
        /// </summary>
        internal static string baseURL {
            get {
                return ResourceManager.GetString("baseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /delete.
        /// </summary>
        internal static string deleteURL {
            get {
                return ResourceManager.GetString("deleteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /get?test=123.
        /// </summary>
        internal static string getURL {
            get {
                return ResourceManager.GetString("getURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /post.
        /// </summary>
        internal static string postURL {
            get {
                return ResourceManager.GetString("postURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /put.
        /// </summary>
        internal static string putURL {
            get {
                return ResourceManager.GetString("putURL", resourceCulture);
            }
        }
    }
}
